### ISSUE TITLE
Not compatible with 1.9.4 yet? (Task#1698 exception)

### ISSUE THREAD

**Issue by PsychoLynx** [TealNerd/RadarJammer#6]
When I join the server, it spams this (using latest build of RJ)

[Server thread/WARN]: [RadarJammer] Task #1698 for RadarJammer v2.3 generated an exception
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_9_R1/entity/CraftPlayer
    at com.biggestnerd.radarjammer.VisibilityManager.getPing(VisibilityManager.java:442) ~[?:?]
    at com.biggestnerd.radarjammer.VisibilityManager.run(VisibilityManager.java:175) ~[?:?]
    at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-8a048fe-042911f]
    at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-8a048fe-042911f]
    at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:734) [spigot.jar:git-Spigot-8a048fe-042911f]
    at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-8a048fe-042911f]
    at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot.jar:git-Spigot-8a048fe-042911f]
    at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot.jar:git-Spigot-8a048fe-042911f]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]

**Comment by TealNerd** [comment]
Yeah the highest version this will work with is 1.9.2, If you need a 1.9.4 version you would only need to change the import for CraftPlayer in VisibilityManager.java and change the dependency in the pom to spigot 1.9.4 (this will require you to run the build tools). 

If you're not sure how to do that stuff I can make a branch for 1.9.4 and set up a build on my jenkins

**Comment by PsychoLynx** [comment]
I would very much appreciate if you could do that as I'm unfortunately more in the end-user camp that the dev camp. Thank you for the quick response!

**Comment by TealNerd** [comment]
[Done](http://dydoisbutts.info:8080/job/RadarJammer%201.9.4/)
